      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Run Android Lint
        run: ./gradlew lintDebug

      - name: Upload Lint Report
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: app/build/reports/lint-results.html

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: app/build/reports/tests/testDebugUnitTest/index.html
